import net.ltgt.gradle.errorprone.CheckSeverity

import java.text.SimpleDateFormat

plugins {
    id 'checkstyle'
    id 'idea'
    id 'java'
    id 'maven-publish'

    id 'com.github.breadmoirai.github-release' version '2.5.2'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.themrmilchmann.curseforge-publish' version '0.11.0'
    id 'net.ltgt.errorprone' version '5.1.0'
    id 'net.neoforged.moddev.legacyforge' version '2.+'
    id 'org.jetbrains.changelog' version '1.3.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

wrapper {
    gradleVersion = '8.14.2'
    distributionType = Wrapper.DistributionType.BIN
}

def isSnapshotVersion = project.hasProperty('teamcityBuild')
def githubUser = 'IntelligenceModding'
def githubRepo = 'AdvancedPeripherals'
def curseforgeProjectId = 431725
def modrinthProjectId = 'SOw6jD6x'

version = "${mod_version}" + (isSnapshotVersion ? "-SNAPSHOT" : "") + "${mod_artifact_suffix}"
group = 'de.srendi.advancedperipherals'

def fullVersionTag = "${minecraft_version}-${project.version}"

def static getenv(path = ".env") {
    def env = [:]

    def file = new File(path)
    if (file.exists()) {
        file.eachLine { line ->
            def (name, value) = line.tokenize("=")
            if (value != null) {
                env[name.trim()] = value.trim()
            }
        }
    }

    return env
}

def secretEnv = getenv()
def curseforgeKey = secretEnv["CURSEFORGE_KEY"] ?: System.getenv("CURSEFORGE_KEY") ?: ''
def modrinthKey = secretEnv["MODRINTH_KEY"] ?: System.getenv("MODRINTH_KEY")
def repositoryName = secretEnv["PUBLIC_REP_NAME"] ?: System.getenv("PUBLIC_REP_NAME")
def repositoryKey = secretEnv["PUBLIC_REP_KEY"] ?: System.getenv("PUBLIC_REP_KEY")
def githubKey = secretEnv["GITHUB_KEY"] ?: System.getenv("GITHUB_KEY")
def minimumRuntime = project.hasProperty('clean_test') && project.property('clean_test').toBoolean()

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

legacyForge {
    // Specify the version of NeoForge to use.
    version = "${neo_version}"

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    validateAccessTransformers = true

    runs {
        // applies to all the run configs below
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    mavenCentral()
    maven {
        name = "Intelligence Mirror Repo"
        url = "https://mvn.intelligence-modding.de/Minecraft"
        content {
            includeGroup("com.refinedmods.refinedstorage")
        }
    }
    maven {
        name = "Blamejared Maven"
        url = "https://maven.blamejared.com"
        content {
            includeGroup("vazkii.botania")
            includeGroup("vazkii.patchouli")
        }
    }
    maven {
        name = "Squiddev Maven"
        url = "https://maven.squiddev.cc"
        content {
            includeGroup("cc.tweaked")
            includeModule("org.squiddev", "Cobalt")
        }
    }
    maven {
        name = "Theillusivec4 Maven"
        url = "https://maven.theillusivec4.top/"
        content {
            includeGroup("top.theillusivec4.curios")
        }
    }
    maven {
        name = "LDT Team minecolonies"
        url = "https://ldtteam.jfrog.io/ldtteam/modding"
        content {
            includeGroup("com.ldtteam")
        }
    }
    maven {
        name = "Modmaven"
        url = "https://modmaven.dev/"
        content {
            includeGroup("mezz.jei")
            includeGroup("appeng")
            includeGroup("mekanism")
        }
    }
    maven {
        name = "Create maven"
        url = "https://maven.createmod.net"
        content {
            includeGroup("com.simibubi.create")
            includeGroup("dev.engine-room.flywheel")
            includeGroup("net.createmod.ponder")
        }
    }
    maven {
        name = "Create Registrate maven"
        url = "https://maven.ithundxr.dev/mirror"
        content {
            includeGroup("com.tterrag.registrate")
        }
    }
    maven {
        name = "TerraformersMC EMI"
        url = "https://maven.terraformersmc.com/"
        content {
            includeGroup("dev.emi")
        }
    }
    maven {
        name = "SirEdvin's private repository"
        url = "https://repo.repsy.io/mvn/siredvin/default"
        content {
            includeGroup("site.siredvin.ttoolkit")
        }
    }
    maven {
        name = "Shedaniel cloth"
        url = "https://maven.shedaniel.me/"
        content {
            includeGroup("dev.architectury")
            includeGroup("me.shedaniel.cloth")
        }
    }
    maven {
        name = "Kotlin for Forge"
        url = "https://thedarkcolour.github.io/KotlinForForge/"
        content {
            includeModule("thedarkcolour", "kotlinforforge")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://cursemaven.com"
            }
        }
        filter {
            includeGroup("curse.maven")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup("maven.modrinth")
        }
    }
}

configurations {
    implementationExtra
    testModImplementation.extendsFrom(implementation)
    testModImplementation.extendsFrom(testImplementation)
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    // If some of the dependencies are not needed in the dev environment, you can comment the `runtimeOnly` line so it
    // will not be included in the client.

    errorprone "com.google.errorprone:error_prone_core:2.42.0"

    // Minimal requirements
    compileOnly "org.jetbrains:annotations:${jb_annotations}"
    modImplementation "cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cc_version}"

    // Minimal requirements end

    modCompileOnly "curse.maven:refined-storage-243076:${refinedstorage_version}"
    if (!minimumRuntime) {
        modRuntimeOnly "curse.maven:refined-storage-243076:${refinedstorage_version}"
    }

    // Extended requirements
    // We don't use the api since we need a specific class from mekanism
    modCompileOnly "mekanism:Mekanism:${mekanism_version}"
    if (!minimumRuntime) {
        modRuntimeOnly "mekanism:Mekanism:${mekanism_version}"
    }

    // Applied Energistics 2
    modCompileOnly "appeng:appliedenergistics2-forge:${appliedenergistics_version}"
    if (!minimumRuntime) {
        modRuntimeOnly "appeng:appliedenergistics2-forge:${appliedenergistics_version}"
    }

    // Applied Mekanistics
    modCompileOnly "curse.maven:applied-mekanistics-574300:${appliedmekanistics_version}"
    if (!minimumRuntime) {
        modRuntimeOnly "curse.maven:applied-mekanistics-574300:${appliedmekanistics_version}"
    }

    // AE2 Things
    modCompileOnly "curse.maven:ae2things-609977:${ae2things_version}-sources"
    if (!minimumRuntime) {
        modRuntimeOnly "curse.maven:ae2things-609977:${ae2things_version}-sources"
    }

    // Create
    modCompileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    modCompileOnly "com.tterrag.registrate:Registrate:${registrate_version}"
    modCompileOnly "dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}"
    modCompileOnly "net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"
    if (!minimumRuntime) {
        modRuntimeOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
        modRuntimeOnly "com.tterrag.registrate:Registrate:${registrate_version}"
        modRuntimeOnly "dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}"
        modRuntimeOnly "net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"
    }

    // Curios
    modCompileOnly "top.theillusivec4.curios:curios-forge:${curios_version}:api"
    if (!minimumRuntime) {
        modRuntimeOnly "top.theillusivec4.curios:curios-forge:${curios_version}"
    }

    // DimStorage
    modCompileOnly "curse.maven:dimstorage-353882:${dimstorage_version}"
    modCompileOnly "curse.maven:edivadlib-638508:${edivadlib_version}"

    // Minecolonies
    modCompileOnly "com.ldtteam:blockui:${blockui_version}"
    modCompileOnly "curse.maven:domum-ornamentum-527361:${domumornamentum_version}"
    modCompileOnly "com.ldtteam:minecolonies:${minecolonies_version}"
    modCompileOnly "com.ldtteam:structurize:${structurize_version}"
    if (!minimumRuntime) {
        modRuntimeOnly "com.ldtteam:blockui:${blockui_version}"
        modRuntimeOnly "curse.maven:domum-ornamentum-527361:${domumornamentum_version}"
        modRuntimeOnly "com.ldtteam:minecolonies:${minecolonies_version}"
        modRuntimeOnly "com.ldtteam:structurize:${structurize_version}"
    }

    // Patchouli
    modCompileOnly "vazkii.patchouli:Patchouli:${patchouli_version}-FORGE"
    if (!minimumRuntime) {
        modRuntimeOnly "vazkii.patchouli:Patchouli:${patchouli_version}-FORGE"
    }

    // Powah
    modCompileOnly "curse.maven:powah-633483:${powah_version}"
    modCompileOnly "dev.architectury:architectury-forge:${architectury_version}"
    if (!minimumRuntime) {
        modRuntimeOnly "me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}"
        modRuntimeOnly "curse.maven:powah-633483:${powah_version}"
    }

    testModImplementation sourceSets.main.output

    // Testing stuffs

    modCompileOnly "org.apiguardian:apiguardian-api:1.1.2" // prevent `warning: unknown enum constant Status.STABLE`
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junit_version}"

    // EMI
    modRuntimeOnly "dev.emi:emi-forge:${emi_version}"
    // Spark
    modRuntimeOnly "maven.modrinth:spark:1.10.53-forge"

    if (!minimumRuntime) {
        // Extended AE
        modRuntimeOnly "curse.maven:ex-pattern-provider-892005:${extended_ae_version}"
        modRuntimeOnly "curse.maven:glodium-957920:${glodium_version}"

        // Sophisticated Backpacks
        modRuntimeOnly "maven.modrinth:sophisticated-backpacks:${sophisticated_backpacks_version}"
        modRuntimeOnly "maven.modrinth:sophisticated-core:${sophisticated_core_version}"
    }
}

changelog {
    version = "${project.version}"
    path = "${project.projectDir}/CHANGELOG.md"
    header = "[${fullVersionTag}] - ${new SimpleDateFormat("yyyy-MM-dd").format(new Date())}"
    // Valid patterns would be:
    //   1.16.5-1.1.1.1b
    //   1.18-1.0r
    //   1.19-1.0.0a
    headerParserRegex = ~/\[?(\d+(?:\.\d+){1,2}-\d+(?:\.\d+){1,3}\w)]?.*/
    itemPrefix = ""
    keepUnreleasedSection = true
    unreleasedTerm = "[Unreleased]"
    groups = []
}

tasks.withType(JavaCompile).configureEach {
    options.errorprone {
        disable(
            "EffectivelyPrivate",
            "EnumOrdinal",
            "FutureReturnValueIgnored",
            "ImmutableEnumChecker",
            "MissingSummary",
            "MutablePublicArray",
            "ReferenceEquality",

            "StringSplitter",
        )
        check("MissingOverride", CheckSeverity.ERROR)
    }
}

afterEvaluate {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xmaxerrs" << "2000"
    }
}

jar {
    manifest({
        attributes(["Specification-Title"     : "advancedperipherals",
                    "Specification-Vendor"    : "Srendi",
                    "Specification-Version"   : "${version}",
                    "Implementation-Title"    : "advancedperipherals",
                    "Implementation-Version"  : "${version}",
                    "Implementation-Vendor"   : "Srendi",
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    })
    archiveFileName = "AdvancedPeripherals-${minecraft_version}-${mod_version}.jar"
}

tasks.withType(Test).configureEach {
    failOnNoDiscoveredTests = false
}

tasks.withType(Checkstyle) {
    reports {
        xml.required = false
        html.required = false
    }
    // Checkstyle is compatible with the configuration cache, however we need to disable it to prevent a build issue with teamcity
    notCompatibleWithConfigurationCache()
    outputs.upToDateWhen { false }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [minecraft_version         : minecraft_version,
                             neo_version               : neo_version,
                             loader_version            : loader_version,
                             mod_id                    : mod_id,
                             version                   : version,
                             cc_version                : cc_version,
                             minecolonies_version      : minecolonies_version,
                             appliedenergistics_version: appliedenergistics_version,
                             patchouli_version         : patchouli_version,
                             mekanism_version          : mekanism_version,
                             ae2things_version         : ae2things_version,
                             powah_version             : powah_version,]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.register("copyBlockTextures", Copy) {
    from 'src/generated/block-textures'
    into "src/generated/resources/assets/${project.mod_id}/textures/block"
}

tasks.named("runData") {
    finalizedBy("copyBlockTextures")
}

tasks.named("processResources") {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

githubRelease {
    releaseAssets = jar.archiveFile

    if (githubKey != null)
        token = githubKey
    owner = githubUser
    repo = githubRepo
    tagName = fullVersionTag
    releaseName = fullVersionTag
    targetCommitish = System.getenv("GITHUB_REF_NAME")
    generateReleaseNotes = false
    try {
        body = project.changelog.get("${fullVersionTag}").withHeader(false).toText()
    } catch (err) {
        System.out.println(err)
        body = ""
    }
    draft = false
    prerelease = release_type.equalsIgnoreCase("alpha")
}

curseforge {
    // This token is used to authenticate with CurseForge. It should be handled
    // with the same level of care and security as your actual password. You
    // should never share your token with an untrusted source or publish it
    // publicly to GitHub or embed it within a project. The best practice is to
    // store this token in an environment variable or a build secret.
    apiToken = curseforgeKey

    publications {
        register('curseForge') {
            projectId = curseforgeProjectId

            def dashVersion = minecraft_version.replace(".", "-")
            def secondDash = dashVersion.indexOf('-', dashVersion.indexOf('-') + 1)
            gameVersion("modloader", "forge")
            gameVersion("minecraft-" + (secondDash == -1 ? dashVersion : dashVersion.substring(0, secondDash)), dashVersion)

            artifacts.register('main') {
                from jar
                displayName = jar.archiveFileName.get()
                releaseType = release_type

                relations {
                    requiredDependency 'cc-tweaked'
                    optionalDependency 'applied-energistics-2'
                    optionalDependency 'create'
                    optionalDependency 'curios'
                    optionalDependency 'dimstorage'
                    optionalDependency 'mekanism'
                    optionalDependency 'minecolonies'
                    optionalDependency 'powah'
                    optionalDependency 'refined-storage'
                }

                changelog {
                    format = io.github.themrmilchmann.gradle.publish.curseforge.ChangelogFormat.MARKDOWN
                    try {
                        content = "${project.changelog.get("${fullVersionTag}").withHeader(false).toText()}"
                    } catch (err) {
                        System.out.println(err)
                        content = ""
                    }
                }
            }
        }
    }
}

modrinth {
    token = modrinthKey
    projectId = modrinthProjectId
    versionNumber = "${fullVersionTag}"
    versionName = "Advanced Peripherals ${minecraft_version} ${version}"
    versionType = release_type
    uploadFile = jar
    gameVersions = [minecraft_version]
    loaders = ["forge"]
    dependencies {
        required.project "cc-tweaked"
    }

    try {
        changelog = project.changelog.get("${fullVersionTag}").withHeader(false).toText()
    } catch (err) {
        System.out.println(err)
        changelog = ""
    }
}

publishing {
    publications { PublicationContainer publicationContainer ->
        publicationContainer.register("maven", MavenPublication) { MavenPublication publication ->
            publication.from((SoftwareComponent) components.java)
            publication.groupId = project.group
            publication.version = isSnapshotVersion ? "${minecraft_version}-${version}-${project.teamcityBuild}" : "${minecraft_version}-${version}"
            publication.artifactId = isSnapshotVersion ? "advancedperipherals-snapshots" : "advancedperipherals"
            publication.artifacts = [jar, sourcesJar]
            publication.pom {
                name.set("AdvancedPeripherals")
                packaging = 'jar'
                description.set(
                    'Advanced Peripherals provides multiple extensions for ComputerCraft in form of Peripherals, Pocket Upgrades, Turtles or new gear.\n' +
                    'It also integrates with multiple third party mods.')
                url.set('https://docs.intelligence-modding.de/')
                scm {
                    url.set("https://github.com/${githubUser}/${githubRepo}.git")
                }
                issueManagement {
                    system.set('github')
                    url.set("https://github.com/${githubUser}/${githubRepo}/issues")
                }
                licenses {
                    license {
                        name.set('Apache-2.0')
                        distribution.set('repo')
                    }
                }
                withXml {
                    NodeList dependencies = asNode().dependencies
                    NodeList allDeps = dependencies.'*'

                    allDeps.<Node> findAll() { Node el ->
                        el.artifactId.text() == 'forge' && el.groupId.text() == 'net.neoforged'
                    }.forEach() { Node el ->
                        el.parent().remove(el)
                    }
                    // remove ForgeGradle's mapped suffix from versions & set as optional so anyone else doesn't inherit them
                    allDeps.<Node> findAll() { Node el ->
                        el.version.text().contains('_mapped_')
                    }.each { Node el ->
                        el.version.each { Node version ->
                            def versionText = version.text()
                            version.setValue(versionText.substring(0, versionText.indexOf('_mapped_')))
                        }
                        el.appendNode('optional', true)
                    }
                }
            }
        }
    }
    repositories {
        maven {
            name = "public"
            url = "https://mvn.intelligence-modding.de/Intelligence"
            credentials {
                username = repositoryName
                password = repositoryKey
            }
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
