org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.logging.level=info

# Minecraft related
mod_id=advancedperipherals
# do not include mod_version/minecraft_version with equals sign anywhere else in the file (even in comments)
# also do not add space around the equal sign
# since we are using poor grep command to do automation :p
mod_version=0.7.50b
minecraft_version=1.21.1
mod_artifact_suffix=
neo_version=21.1.140
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
loader_version=4
release_type=alpha
jb_annotations=21.0.1

# Test dependencies
junit_version=5.7.2
hamcrest_version=2.2
kotlin_version=1.9.22
kotlinx_coroutines_version=1.6.0-RC3
ttoolkit_version=0.1.3

# Mod dependencies
cc_version=1.115.1

ae2things_version=5637783
appliedenergistics_version=19.2.10
appliedmekanistics_version=5978711
refinedstorage_version=2.0.0-beta.2
refinedstorage_mekanism_version=1.0.0
minecolonies_version=1.1.978-1.21.1-snapshot
patchouli_version=1.21-88
mekanism_version=1.21.1-10.7.12.77
powah_version=6143661

# Mod dependencies which are needed for other mods
# minecolonies
structurize_version=1.0.775-1.21.1-snapshot
multipiston_version=1.2.51-1.21.1-snapshot
blockui_version=1.0.199-1.21.1-snapshot
domumornamentum_version=1.0.204-1.21.1-snapshot
# refined storage mek integration
emiVersion=1.1.11+1.21
# powah
cloth_config_version=15.0.127

# Mod dependencies for testing stuff(Only used in the dev environment)
jei_version=1.21.1-neoforge:19.19.6.235
createadditions_version=5099752