org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4G
org.gradle.logging.level=info

# Minecraft related
mod_id=advancedperipherals
# do not include mod_version/minecraft_version with equals sign anywhere else in the file (even in comments)
# also do not add space around the equal sign
# since we are using poor grep command to do automation :p
mod_version=0.8.0a
minecraft_version=1.20.1
mod_artifact_suffix=
neo_version=1.20.1-47.1.47
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
loader_version=4
release_type=alpha
jb_annotations=21.0.1

# Test dependencies
hamcrest_version=2.2
junit_version=5.14.3
kotlin_version=1.9.22
kotlinx_coroutines_version=1.6.0-RC3
ttoolkit_version=0.1.3

# Mod dependencies

# Hard dependencies
cc_version=1.119.0

# Soft dependencies
ae2things_version=4616683
appliedenergistics_version=15.4.10
appliedmekanistics_version=7244744
architectury_version=9.0.8
create_version=6.0.8-289
curios_version=5.14.1+1.20.1
dimstorage_version=4717497
flywheel_version=1.0.5
mekanism_version=1.20.1-10.4.16.80
minecolonies_version=1.20.1-1.1.1276
patchouli_version=1.20.1-85
ponder_version=1.0.91
powah_version=6828054
refinedstorage_version=4844585
registrate_version=MC1.20-1.3.3

# Mod dependencies which are needed for other mods
# dimstorage
edivadlib_version=4717006
# minecolonies
blockui_version=1.20.1-1.0.194-snapshot
domumornamentum_version=7585567
multipiston_version=1.20-1.2.43
structurize_version=1.20.1-1.0.818
# powah
cloth_config_version=11.1.136

# Mod dependencies for testing stuff (Only used in the dev environment)
createadditions_version=7208610
emi_version=1.1.24+1.20.1
extended_ae_version=8615273
glodium_version=5226922
sophisticated_backpacks_version=1.20.1-3.24.67.2109
sophisticated_core_version=1.20.1-1.3.83.2295
