org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.logging.level=info

# Minecraft related
mod_id=advancedperipherals
# do not include mod_version/minecraft_version with equals sign anywhere else in the file (even in comments)
# also do not add space around the equal sign
# since we are using poor grep command to do automation :p
mod_version=0.7.57b
minecraft_version=1.21.1
mod_artifact_suffix=
neo_version=21.1.200
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
loader_version=4
release_type=beta
jb_annotations=21.0.1

# Test dependencies
junit_version=5.7.2
hamcrest_version=2.2
kotlin_version=1.9.22
kotlinx_coroutines_version=1.6.0-RC3
ttoolkit_version=0.1.3

# Mod dependencies
cc_version=1.116.2

ae2things_version=5637783
appliedenergistics_version=19.2.13
appliedmekanistics_version=5978711
mekanism_version=1.21.1-10.7.15.81
minecolonies_version=1.1.1230-1.21.1-snapshot
patchouli_version=1.21-88
powah_version=6143661
refinedstorage_mekanism_version=1.1.0
refinedstorage_version=2.0.0

# Mod dependencies which are needed for other mods
# minecolonies
blockui_version=1.0.199-1.21.1-snapshot
domumornamentum_version=1.0.223-snapshot
multipiston_version=1.2.51-1.21.1-snapshot
structurize_version=1.0.796-1.21.1-snapshot
# powah
cloth_config_version=15.0.127

# Mod dependencies for testing stuff(Only used in the dev environment)
create_version=6.0.8-168
createadditions_version=5099752minecraft_version = 1.21.1
emi_version=1.1.22+1.21.1
flywheel_version=1.0.5
ponder_version=1.0.64
registrate_version=MC1.21-1.3.0+62
